title: Quy Tran # your name (or website title) here
logo: "/images/Quy.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Creative Data Scientist| Business Analyst| Customer Relations  
  <br><br>
  Solutions Driven| Proficiency and Effectiveness Focus Mindset
  <br><br>
  Love: God, Dog, Art, Good Book, thought-provoking, gadgets (application of technology)<br>
  <a href="https://www.linkedin.com/in/quyttran/">View My LinkedIn Profile</a> 


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
